import { createReadStream } from "fs";
import { stat } from "fs/promises";
import path from "path";
import { NextResponse } from "next/server";
import { Readable } from "stream";
import { UPLOAD_DIR } from "@/lib/uploads";

export const runtime = "nodejs";

const CONTENT_TYPES: Record<string, string> = {
  ".jpg": "image/jpeg",
  ".png": "image/png",
  ".webp": "image/webp",
  ".heic": "image/heic",
  ".mp4": "video/mp4",
  ".mov": "video/quicktime",
  ".webm": "video/webm",
  ".svg": "image/svg+xml",
};

/**
 * Serves guest photos and videos from the upload directory.
 *
 * In production that directory is a mounted volume outside `public/`, which
 * Next will not serve on its own. Videos are streamed with range support so a
 * guest can scrub a clip without downloading all of it first.
 */
export async function GET(
  request: Request,
  { params }: { params: Promise<{ file: string }> }
) {
  const { file } = await params;

  // Names are generated by saveUpload; anything with a path separator or a
  // traversal segment did not come from us.
  const name = path.basename(file);
  if (name !== file || name.startsWith(".")) {
    return NextResponse.json({ error: "Not found." }, { status: 404 });
  }

  const extension = path.extname(name).toLowerCase();
  const contentType = CONTENT_TYPES[extension];
  if (!contentType) {
    return NextResponse.json({ error: "Not found." }, { status: 404 });
  }

  const fullPath = path.join(UPLOAD_DIR, name);
  let info;
  try {
    info = await stat(fullPath);
  } catch {
    return NextResponse.json({ error: "Not found." }, { status: 404 });
  }
  if (!info.isFile()) {
    return NextResponse.json({ error: "Not found." }, { status: 404 });
  }

  const headers: Record<string, string> = {
    "Content-Type": contentType,
    "Cache-Control": "public, max-age=31536000, immutable",
    "Accept-Ranges": "bytes",
  };

  const range = request.headers.get("range");
  const rangeMatch = range?.match(/^bytes=(\d*)-(\d*)$/);
  if (rangeMatch) {
    const start = rangeMatch[1] ? Number(rangeMatch[1]) : 0;
    const end = rangeMatch[2] ? Number(rangeMatch[2]) : info.size - 1;

    if (start >= info.size || end >= info.size || start > end) {
      return new NextResponse(null, {
        status: 416,
        headers: { "Content-Range": `bytes */${info.size}` },
      });
    }

    const stream = createReadStream(fullPath, { start, end });
    return new NextResponse(Readable.toWeb(stream) as ReadableStream, {
      status: 206,
      headers: {
        ...headers,
        "Content-Range": `bytes ${start}-${end}/${info.size}`,
        "Content-Length": String(end - start + 1),
      },
    });
  }

  const stream = createReadStream(fullPath);
  return new NextResponse(Readable.toWeb(stream) as ReadableStream, {
    headers: { ...headers, "Content-Length": String(info.size) },
  });
}
